name: Trigger Jenkins job

on: push

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Jobs triggered
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "maven-deploy"
